version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iglesia_app
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    networks:
      - iglesia_network:
        aliases:
          - app

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: http --domain=able-prawn-singularly.ngrok-free.app app:3000
    env_file:
      - .env.production
    environment:
      NGROK_AUTHTOKEN: 2xeBV4WOMbo0Jrv0Qmybz1AEESW_28gkJhf6aLr5PqNDYQZNS
    depends_on:
      - app
    networks:
      - iglesia_network

networks:
  iglesia_network:
    driver: bridge